- name: 小背驰-大推笔
  factors:
    - signals_all:
        - key: F1_D1-MACD面积背驰_BS
          value: 底_5笔_other
          score: 70
      signals_any:
        - key: F3_D1-MACD面积背驰_BS
          value: 底_5笔_other
          score: 70
        - key: F5_D1-MACD面积背驰_推笔
          value: 底_5笔_other
          score: 70
        - key: F15_D1-MACD面积背驰_推笔
          value: 底_5笔_other
          score: 70
        - key: F60_D1-MACD面积背驰_推笔
          value: 底_5笔_other
          score: 70
      name: 'F1-底背+大推'
      enable_notify: true

    - signals_all:
        - key: F3_D1-MACD面积背驰_BS
          value: 底_5笔_other
          score: 70
      signals_any:
        - key: F5_D1-MACD面积背驰_推笔
          value: 底_5笔_other
          score: 70
        - key: F15_D1-MACD面积背驰_推笔
          value: 底_5笔_other
          score: 70
        - key: F60_D1-MACD面积背驰_推笔
          value: 底_5笔_other
          score: 70
      name: 'F3-底背+大推'
      enable_notify: true
  operate: HL
  enable_notify: true
