- name: F1小背驰-大推笔
  operate: HL
  enable_notify: true
  signals_any:
    - key: F1_D1-MACD面积背驰_BS
      value: 顶_5笔_other
      score: 70
    - key: F1_D1-MACD面积背驰_BS
      value: 顶_7笔_other
      score: 70
    - key: F1_D1-MACD面积背驰_BS
      value: 顶_9笔_other
      score: 70
  factors:
    - signals_all:
        - key: F3_D1-MACD面积背驰_推笔
          value: 顶_3笔_other
          score: 70
    - signals_all:
        - key: F3_D1-MACD面积背驰_推笔
          value: 顶_5笔_other
          score: 70
    - signals_all:
        - key: F3_D1-MACD面积背驰_推笔
          value: 顶_7笔_other
          score: 70
    - signals_all:
        - key: F3_D1-MACD面积背驰_推笔
          value: 顶_9笔_other
          score: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_推笔
          value: 顶_3笔_other
          score: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_推笔
          value: 顶_5笔_other
          score: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_推笔
          value: 顶_7笔_other
          score: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_推笔
          value: 顶_9笔_other
          score: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_3笔_other
          score: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_5笔_other
          score: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_7笔_other
          score: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_9笔_other
          score: 70

- name: F3小背驰-大推笔
  operate: HL
  enable_notify: true
  signals_any:
    - key: F3_D1-MACD面积背驰_BS
      value: 顶_5笔_other
      score: 70
    - key: F3_D1-MACD面积背驰_BS
      value: 顶_7笔_other
      score: 70
    - key: F3_D1-MACD面积背驰_BS
      value: 顶_9笔_other
      score: 70
  factors:
    - signals_all:
        - key: F5_D1-MACD面积背驰_推笔
          value: 顶_3笔_other
          score: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_推笔
          value: 顶_5笔_other
          score: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_推笔
          value: 顶_7笔_other
          score: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_推笔
          value: 顶_9笔_other
          score: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_3笔_other
          score: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_5笔_other
          score: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_7笔_other
          score: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_9笔_other
          score: 70


- name: F5小背驰-大推笔
  operate: HL
  enable_notify: true
  signals_any:
    - key: F5_D1-MACD面积背驰_BS
      value: 顶_5笔_other
      score: 70
    - key: F5_D1-MACD面积背驰_BS
      value: 顶_7笔_other
      score: 70
    - key: F5_D1-MACD面积背驰_BS
      value: 顶_9笔_other
      score: 70
  factors:
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_3笔_other
          score: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_5笔_other
          score: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_7笔_other
          score: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_推笔
          value: 顶_9笔_other
          score: 70
