- name: F1小底背-大底背
  signals_any:
    - key: F1_D1-MACD面积背驰_BS
      value: 底_5笔_other
      figure: 70
    - key: F1_D1-MACD面积背驰_BS
      value: 底_7笔_other
      figure: 70
    - key: F1_D1-MACD面积背驰_BS
      value: 底_9笔_other
      figure: 70
  operate: HL
  enable_notify: true
  factors:
    - signals_all:
        - key: F3_D1-MACD面积背驰_BS
          value: 底_5笔_other
          figure: 70
    - signals_all:
        - key: F3_D1-MACD面积背驰_BS
          value: 底_7笔_other
          figure: 70
    - signals_all:
        - key: F3_D1-MACD面积背驰_BS
          value: 底_9笔_other
          figure: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_BS
          value: 底_5笔_other
          figure: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_BS
          value: 底_7笔_other
          figure: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_BS
          value: 底_9笔_other
          figure: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_BS
          value: 底_5笔_other
          figure: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_BS
          value: 底_7笔_other
          figure: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_BS
          value: 底_9笔_other
          figure: 70
      enable_notify: true


- name: F3小底背-大底背
  signals_any:
    - key: F3_D1-MACD面积背驰_BS
      value: 底_5笔_other
      figure: 70
    - key: F3_D1-MACD面积背驰_BS
      value: 底_7笔_other
      figure: 70
    - key: F3_D1-MACD面积背驰_BS
      value: 底_9笔_other
      figure: 70
  operate: HL
  enable_notify: true
  factors:
    - signals_all:
        - key: F5_D1-MACD面积背驰_BS
          value: 底_5笔_other
          figure: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_BS
          value: 底_7笔_other
          figure: 70
    - signals_all:
        - key: F5_D1-MACD面积背驰_BS
          value: 底_9笔_other
          figure: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_BS
          value: 底_5笔_other
          figure: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_BS
          value: 底_7笔_other
          figure: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_BS
          value: 底_9笔_other
          figure: 70
      enable_notify: true


- name: F5小底背-大底背
  signals_any:
    - key: F5_D1-MACD面积背驰_BS
      value: 底_5笔_other
      figure: 70
    - key: F5_D1-MACD面积背驰_BS
      value: 底_7笔_other
      figure: 70
    - key: F5_D1-MACD面积背驰_BS
      value: 底_9笔_other
      figure: 70
  operate: HL
  enable_notify: true
  factors:
    - signals_all:
        - key: F15_D1-MACD面积背驰_BS
          value: 底_5笔_other
          figure: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_BS
          value: 底_7笔_other
          figure: 70
    - signals_all:
        - key: F15_D1-MACD面积背驰_BS
          value: 底_9笔_other
          figure: 70
      enable_notify: true
