// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::{Identifiable, Queryable, Selectable};

#[derive(Queryable, Debug, Clone, Selectable, Identifiable)]
#[diesel(primary_key(exchange, symbol))]
#[diesel(table_name = crate::schema::symbols)]
#[diesel(check_for_backend(diesel::sqlite::Sqlite))]
pub struct Symbol {
    pub screener: Option<String>,
    pub type_: Option<String>,
    pub pricescale: Option<i32>,
    pub exchange: Option<String>,
    pub symbol: Option<String>,
    pub logoid: Option<String>,
    pub desc: Option<String>,
}
