[package]
name = "moomoo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
pbjson = "0.6.0"
pbjson-types = "0.6.0"
prost = "0.12"
serde = "1.0.197"
# Only necessary if using Protobuf well-known types:
prost-types = "0.12"
[build-dependencies]
prost-build = "0.12.3"
pbjson-build = "0.6.2"